version: "3.8"
services:
  web:
    image: nginx:1.18
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/public:/app/public
    depends_on:
      - app
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./infra/ruby/Dockerfile
    tty: true
    stdin_open: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    volumes:
      - ./infra/mariadb/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - dbvol:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_development
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "9000:8080"
    depends_on:
      - db
volumes:
  dbvol:
